--DROP TABLE SQLTOOL_SQL;
CREATE TABLE SQLTOOL_SQL (
  ID            SERIAL        PRIMARY KEY,
  KIND          INT           NOT NULL DEFAULT 1,
  NAME          VARCHAR(256)  NOT NULL,
  GROUPNAME     VARCHAR(1024) NOT NULL,
  SQLTEXT       TEXT          NOT NULL,
  DESCRIPTION   TEXT,
  SETTING       TEXT,
  INSERT_DATE   TIMESTAMP     NOT NULL,
  UPDATE_DATE   TIMESTAMP     NOT NULL
)
;

