--DROP TABLE SQLTOOL_SQL;
CREATE TABLE SQLTOOL_SQL (
  ID            SERIAL        PRIMARY KEY,
  NAME          VARCHAR(256)  NOT NULL,
  GROUPNAME     VARCHAR(1024),
  SQLTEXT       TEXT          NOT NULL,
  INSERT_DATE   TIMESTAMP     NOT NULL,
  UPDATE_DATE   TIMESTAMP     NOT NULL
)
;

